allauthdemo/polls/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'polls'

#urlpatterns = [
#  url(r'^$', views.index, name='index'),
  # ex: /polls/5/
#  url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
  # ex: /polls/5/results/
#  url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
  # ex: /polls/5/vote/
#  url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#]

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),
]

allauthdemo/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', login_required(views.EventListView.as_view()), name='index'),
    url(r'^create/$', login_required(views.create_event), name='create-event'),
    url(r'^(?P<pk>[0-9a-f-]+)/$', login_required(views.EventDetailView.as_view()), name='view-event'),
    url(r'^(?P<pk>[0-9a-f-]+)/polls/$', login_required(views.EventDetailPollsView.as_view()), name='event-polls'),
    url(r'^(?P<pk>[0-9a-f-]+)/entities/$', login_required(views.EventDetailEntitiesView.as_view()), name='event-entities'),
    url(r'^(?P<pk>[0-9a-f-]+)/results/$', login_required(views.EventDetailResultsView.as_view()), name='event-results'),
    url(r'^(?P<pk>[0-9a-f-]+)/advanced/$', login_required(views.EventDetailAdvancedView.as_view()), name='event-advanced'),
    url(r'^(?P<event_id>[0-9a-f-]+)/end/$', login_required(views.event_end), name='end-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/edit/$', login_required(views.edit_event), name='edit-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/delete/$', login_required(views.del_event), name='del-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/decrypt/$', views.event_trustee_decrypt, name='decrypt-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/prepare/$', views.event_trustee_setup, name='prepare-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/bulletin_board/$', views.bulletin_boards, name='bulletin-boards'),
    url(r'^(?P<event_id>[0-9a-f-]+)/bulletin_board/(?P<poll_id>[0-9a-f-]+)/$', views.bulletin_board, name='bulletin-board'),
    url(r'^(?P<event_id>[0-9a-f-]+)/bulletin_board/(?P<poll_id>[0-9a-f-]+)/voter/(?P<voter_alias>[0-9a-f-]+)/$', views.voter_board, name='voter-board'),
    url(r'^(?P<event_id>[0-9a-f-]+)/poll/(?P<poll_id>[0-9a-f-]+)/vote/$', views.event_vote, name='event-vote'),
    url(r'^(?P<event_id>[0-9a-f-]+)/create/poll/$', login_required(views.manage_questions), name='create-poll'),
    url(r'^(?P<event_id>[0-9a-f-]+)/poll/(?P<poll_id>[0-9a-f-]+)/edit$', login_required(views.edit_poll), name='edit-poll'),
    url(r'^audit/$', views.vote_audit, name='vote_audit')
]

allauthdemo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

import allauthdemo.views
import allauthdemo.auth.views
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='visitor/landing-index.html'), name='landing_index'),
    url(r'^about$', TemplateView.as_view(template_name='visitor/landing-about.html'), name='landing_about'),
    url(r'^terms/$', TemplateView.as_view(template_name='visitor/terms.html'), name='website_terms'),
    url(r'^contact$', TemplateView.as_view(template_name='visitor/contact.html'), name='website_contact'),

    url(r'^event/', include('allauthdemo.polls.urls', namespace="polls")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', allauthdemo.auth.views.account_profile, name='account_profile'),

    url(r'^member/$', allauthdemo.views.member_index, name='user_home'),
    url(r'^member/events$', allauthdemo.views.MemberEvents.as_view(), name='account_events'),
    url(r'^member/action$', allauthdemo.views.member_action, name='user_action'),

    url(r'^admin/', include(admin.site.urls))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

allauthdemo/polls/polls/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

import datetime

from django.utils import timezone

class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')

  def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

  was_published_recently.admin_order_field = 'pub_date'
  was_published_recently.boolean = True
  was_published_recently.short_description = 'Published recently?'

  def __str__(self):
    return self.question_text

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

allauthdemo/polls/polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render

from django.utils import timezone

from .models import Question, Choice

from django.views import generic


""" from allauthdemo.auth.forms import RegistrationForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegistrationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegistrationForm()

    return render(request, 'polls/index.html', {'form': form}) """


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
# ...
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

allauthdemo/views.py
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views import generic
from allauthdemo.polls.models import Event
from django.shortcuts import render_to_response


@login_required
def member_index(request):
    return render_to_response("member/member-index.html", RequestContext(request))


class MemberEvents(generic.ListView):
    model = Event
    template_name = 'member/member-events.html'

    def get_context_data(self, **kwargs):
        context = super(MemberEvents, self).get_context_data(**kwargs)
        # no check needed for anon, as url should make sure we're logged in!
        return context

    def get_queryset(self):
        return self.request.user.organisers.all()


@login_required
def member_action(request):
    return render_to_response("member/member-action.html", RequestContext(request))

allauthdemo/templates/polls/bulletin_board.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div id="pageHeader">
            <!-- Heading -->
            <h2>Bulletin Boards for the Event: {{event.title}}</h2>
            <!-- Action Buttons -->
            {% comment %}<div class="col-xs-5 col-sm-3 col-md-3 marginTopEditButton">
                <a href="{% url 'polls:vote_audit' %}" class="btn btn-primary" style="float: right; margin-right: 0.4em;">
                    <span class="glyphicon glyphicon-qrcode"></span> Audit Ballot
                </a>
            </div>{% endcomment %}
        </div>
        <div id="pageBody">
            <br>
            <p>This page groups together all of the bulletin boards for each poll of the event. Within each board you
            can audit your own votes.</p>
            <br>
            <div class="form-group">
               <table id="bbs-table" class="table table-hover">
                  <thead>
                    <tr>
                        <th class="text-center">Poll</th>
                        <th class="text-center">No. Votes</th>
                        <th class="text-center">No. Voters</th>
                        <th class="text-center">Turnout</th>
                        <th class="text-center">View</th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for poll in event.polls.all %}
                           <tr>
                               <td class="text-center">{{ poll.question_text }}</td>
                               <td class="text-center">{{ poll.total_votes }}</td>
                               <td class="text-center">TODO</td>
                               <td class="text-center">TODO</td>
                               <td class="text-center">
                                   <a href="{% url 'polls:vote_audit' %}">View</a>
                               </td>
                           </tr>
                        {% endfor %}
                  </tbody>
               </table>
            </div>

        </div>
    </div>
{% endblock %}

allauthdemo/templates/polls/bulletin_boards.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div id="pageHeader">
            <!-- Heading -->
            <h2>Bulletin Boards for the Event: {{event.title}}</h2>
        </div>
        <div id="pageBody">
            <hr>
            <p>This page groups together all of the bulletin boards for each poll of the event. Within each board you
            can audit your own votes.</p>
            <br>
            <div class="form-group">
               <table id="bbs-table" class="table table-hover">
                  <thead>
                    <tr>
                        <th class="text-center">Poll</th>
                        <th class="text-center">No. Votes</th>
                        <th class="text-center">No. Voters</th>
                        <th class="text-center">Turnout</th>
                        <th class="text-center">View</th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for poll in event.polls.all %}
                           <tr>
                               <td class="text-center">{{ poll.question_text }}</td>
                               <td class="text-center">{{ poll.total_votes }}</td>
                               <td class="text-center">
                                   {% load custom_filters_tags %}
                                   {{ poll.uuid|get_total_num_voters }}
                               </td>
                               <td class="text-center">
                                   {{ poll.uuid|get_turnout }}%
                               </td>
                               <td class="text-center">
                                   <a href="{% url 'polls:bulletin-board' event.uuid poll.uuid %}" class="btn btn-primary">
                                       <span class="glyphicon glyphicon-th-list"></span> View
                                   </a>
                               </td>
                           </tr>
                        {% endfor %}
                  </tbody>
               </table>
            </div>

        </div>
    </div>
{% endblock %}

allauthdemo/templates/polls/create_option.html
{% load crispy_forms_tags %}

<div class="formset">
    {% crispy formset helper %}
    <button type="button" class="btn btn-default add-another-btn" name="add" value="Add another">Add</button>
</div>

allauthdemo/templates/polls/create_poll.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
 <h1>Create Poll for {{event.title}}</h1>
 {% load crispy_forms_tags %}
 <form method="post" action="" class="">
    {% crispy question_form %}
    <input class="btn btn-default" type="submit" value="Submit"/>
</form>
</div>


{% endblock %}

allauthdemo/templates/polls/detail.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
 <h1>{{ question.question_text }}</h1>

 {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

 <form action="{% url 'polls:vote' question.id %}" method="post">
   {% csrf_token %}
   {% for choice in question.choice_set.all %}
     <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
     <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
   {% endfor %}
   <input type="submit" value="Vote" />
 </form>
</div>

{% endblock %}

allauthdemo/templates/polls/event_detail_details.html
{% extends "polls/event_detail_base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block event_nav_details %}active{% endblock %}
{% block event_content %}
    <br/>
    <span><strong>Start Time:</strong> {{ event.start_time_formatted_utc }}</span>
    <br />
    <span><strong>End Time:</strong> {{ event.end_time_formatted_utc }}</span>
    <br/>
    <br/>
    <span><strong>Number of Polls:</strong> {{ event.polls.count }}</span>
    <br/>
    <span><strong>Number of Organisers:</strong> {{ event.users_organisers.count }}</span>
    <br/>
    <span><strong>Number of Trustees:</strong> {{ event.users_trustees.count }}</span>
    <br/>
    <span><strong>Number of Voters:</strong> {{ event.voters.count }}</span>
{% endblock %}

allauthdemo/templates/polls/event_detail_entities.html
{% extends "polls/event_detail_base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block event_nav_organisers %}active{% endblock %}
{% block event_content %}
    <h2>Event Organisers ({{ object.users_organisers.all.count }})</h2>
    <hr/>
  {% if object.users_organisers.all %}
    <ul class="list-group">
      {% for user in object.users_organisers.all %}
      <li class="list-group-item">{{ user.email }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No organisers for this Event.</p>
  {% endif %}
    <hr/>
    <h2>Event Trustees ({{ object.users_trustees.all.count }})</h2>
    <hr/>
  {% if object.users_trustees.all %}
    <ul class="list-group">
      {% for user in object.users_trustees.all %}
      <li class="list-group-item">{{ user.email }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No trustees for this Event.</p>
  {% endif %}
    <hr/>
    <h2>Voters ({{ object.voters.all.count }})</h2>
    <hr/>
  {% if object.voters.all %}
    <ul class="list-group">
      {% for voter in object.voters.all %}
      <li class="list-group-item">{{ voter.email }}</li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No voters for this Event.</p>
    {% endif %}
{% endblock %}

allauthdemo/templates/polls/event_detail_organisers.html
{% extends "polls/event_detail_base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block event_nav_organisers %}active{% endblock %}
{% block event_content %}
    <h2>Event Organisers</h2>
    <hr/>
  {% if object.users_organisers.all %}
    <ul class="list-group">
      {% for user in object.users_organisers.all %}
      <li class="list-group-item">{{ user.email }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No organisers for this Event.</p>
  {% endif %}
    <hr/>
    <h2>Event Trustees</h2>
    <hr/>
  {% if object.users_trustees.all %}
    <ul class="list-group">
      {% for user in object.users_trustees.all %}
      <li class="list-group-item">{{ user.email }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No trustees for this Event.</p>
  {% endif %}
    <hr/>
    <h2>Voters</h2>
    <hr/>
  {% if object.voters.all %}
    <ul class="list-group">
      {% for voter in object.voters.all %}
      <li class="list-group-item">{{ voter.email }}</li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No voters for this Event.</p>
    {% endif %}
{% endblock %}

allauthdemo/templates/polls/event_list.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}

{% block content %}

 <div class="container">
    <div class="form-group">
        <!-- Heading -->
        <div class="col-xs-5 col-sm-3 col-md-2">
            <h1>Events</h1>
        </div>
        <!-- Create Button -->
        <div class="col-xs-7 col-sm-9 col-md-10 marginTopCreateButton">
            <a href="{% url 'polls:create-event' %}" class="btn btn-primary" style="float:right">
                  <span class="glyphicon glyphicon-plus"></span> Create New
            </a>
        </div>
    </div>
   {% if object_list %}
       <div class="form-group">
           <table id="event-list-table" class="table table-hover marginTopEventList">
              <thead>
                <tr>
                    <th class="text-center">Event</th>
                    <th class="text-center">Duration</th>
                    <th class="text-center">No. Polls</th>
                    <th class="text-center">Actions</th>
                    <th class="text-center">Status</th>
                </tr>
              </thead>
              <tbody>
                    {% for event in object_list %}
                   <tr>
                       <td class="text-center"><a href="{% url 'polls:view-event' event.uuid %}">{{ event.title }}</a></td>
                       <td class="text-center">{{ event.duration }}</td>
                       <td class="text-center">{{ event.polls.count }}</td>
                       <td class="text-center">
                           <a href="{% url 'polls:edit-event' event.uuid %}">
                              <span class="btn btn-default glyphicon glyphicon-pencil"></span>
                           </a>
                           <a href="{% url 'polls:del-event' event.uuid %}">
                              <span class="btn btn-default glyphicon glyphicon-trash"></span>
                           </a>
                       </td>
                       <td class="text-center">
                           <div class="btn statusBtn
                                       {% if event.status == 'Future' %}btn-info{% endif %}
                                       {% if event.status == 'Prepared' %}btn-info{% endif %}
                                       {% if event.status == 'Active' %}btn-success{% endif %}
                                       {% if event.status == 'Expired' %}btn-danger{% endif %}
                                       {% if event.status == 'Ended' %}btn-danger{% endif %}
                                       {% if event.status == 'Decrypted' %}btn-primary{% endif %}
                                        ">
                               {{ event.status }}
                           </div>
                       </td>
                   </tr>
                    {% endfor %}
              </tbody>
           </table>
       </div>
   {% else %}
     <div class="col-xs-12 col-sm-12 col-md-12">
        <h4>There are currently no events.</h4>
    </div>
   {% endif %}
 </div>

{% endblock %}

allauthdemo/templates/polls/event_results.html
{% extends "polls/event_detail_base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block event_nav_results %}active{% endblock %}
{% block event_content %}
    {% for poll_result in event_results %}
        <div class="form-group">
            <h3 class="marginTopResultTable">{{ poll_result.name }}</h3>
            <table id="results-table-{{ forloop.counter }}" class="table table-hover">
              <thead>
                <tr>
                    <th class="resultsCol text-center">Option</th>
                    <th class="resultsCol text-center">Votes</th>
                </tr>
              </thead>
              <tbody>
                {% for option in poll_result.options %}
                   <tr>
                       <td class="resultsCol text-center">{{ option.option }}</td>
                       <td class="resultsCol text-center">{{ option.votes }}</td>
                   </tr>
                {% endfor %}
              </tbody>
           </table>
       </div>
    {% endfor %}
{% endblock %}

allauthdemo/templates/polls/event_vote.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block app_js_vars %}
    const OPTION_COUNT = {{ object.options.count }};
    const MIN_SELECTIONS = {{ min_selection }};
    const MAX_SELECTIONS = {{ max_selection }};
    const POLL_COUNT = {{ poll_count }};
    const POLL_NUM = {{ poll_num }};
    var selectedCount = 0;
{% endblock %}

{% block content %}

<div class="container">
    {% if can_vote %}
        <!-- Hidden fields -->
        {% csrf_token %}
        <input id="event-param" type="text" value="{{event.EID}}" hidden/>
        <input id="comb_pk" type="text" value="{{event.public_key}}" hidden/>

        <!-- Event info and instructions -->
        <h2>Event Voting Page for the Event '{{ object.event.title }}'</h2>
        <hr/>
        <div class="alert alert-warning" role="alert" style="margin-top: 1em;">
            You are voting as: <strong>{{ voter_email }}</strong> - Ensure this is correct and don't share this URL!
        </div>
        <span><strong>Voting status:</strong>
            {% if has_voted %}
                <span style="color: green; font-weight: bold">Voted - Re-submitting will change your vote</span>
            {% else %}
                <span style="color: red; font-weight: bold">Not Voted</span>
            {% endif %}
        </span>
        <br/>
        <br/>
        <span><strong>Instructions:</strong>
            You will be shown each poll for this event one by one where you will need to make a selection for the current
            poll before moving onto the next poll. <strong>For this specific poll</strong> you need to make a <strong>
            minimum</strong> of {{ min_selection }} option selection(s) and a <strong>maximum</strong> of
            {{ max_selection }}.

            {% if min_selection == 0 %}
                <br/><br/>Due to the fact that you are permitted to select nothing, simply hitting submit will submit a
                'blank' vote so please be aware of this. You can always re-visit this page before the event ends if you
                change your mind.
            {% endif %}

            <br/><br/>Please make your choice below.
        </span>

        <!-- Poll Voting Section -->
        <p id="poll-num" hidden>{{ poll_num}}</p>
        <h3>Poll {{ poll_num }} of {{ poll_count }}: {{object.question_text}}</h3>
        <hr/>

        {% load crispy_forms_tags %}
         <div class="panel panel-default">
           <div class="panel-heading"><strong>Options</strong></div>
           <div class="panel panel-body">
             {% for option in object.options.all %}
                 <div class="checkbox">
                    {% load custom_filters_tags %}
                    <label id="{{forloop.counter|get_ballot_value:object.options.all.count}}">
                        <input type="checkbox" value="{{forloop.counter|get_ballot_value:object.options.all.count}}">{{ option.choice_text }}
                    </label>
                 </div>
             {% endfor %}
             <hr/>
            <div id="ballot-gen-progress-area">
                <button id="gen-ballots-btn" class="btn btn-primary">Begin Voting</button>
                <!-- Progress bar which is used during encryption -->
                <h4 id="progress-bar-description" class="hidden">Generating 2 Digital Ballots. Please wait...</h4>
                <div id="progress-bar-container" class="progress hidden">
                  <div id="progress-bar" class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                    <span class="sr-only">70% Complete</span>
                  </div>
                </div>
            </div>
           </div>
         </div>

        <!-- Poll Navigation -->
        <div class="panel panel-body">
          {% if prev_uuid %}
            <a href="{% url 'polls:event-vote' event_id=object.event.uuid poll_id=prev_uuid %}?key={{ a_key }}" class="btn btn-danger"
               role="button">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Previous Poll
            </a>
          {% endif %}
          {% if next_uuid %}
            <a href="{% url 'polls:event-vote' event_id=object.event.uuid poll_id=next_uuid %}?key={{ a_key }}" class="btn btn-primary"
               role="button" style="float: right;">
                Next Poll <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            </a>
          {% endif %}
        </div>

        <!-- Information Dialog called upon request -->
        <div class="modal fade" id="modalDialog" role="dialog" tabindex="-1" data-backdrop="static">
            <div class="modal-dialog" role="document">

              <!-- Dialog content-->
              <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" style="text-align: center"><strong>Please Select a Ballot</strong></h4>
                </div>
                <div class="modal-body">
                    <div class="choice-group">
                        <a id="choice-A" class="btn btn-sq btn-primary">
                            A
                        </a>
                        <a id="choice-B" class="btn btn-sq btn-warning choice">
                            B
                        </a>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="nextDialogBtn" type="button" class="btn btn-primary">Next</button>
                    <button id="cancelDialogBtn" type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    <button id="closeDialogBtn" type="button" class="btn btn-primary hidden" data-dismiss="modal">Close</button>
                    <button id="startOverDialogBtn" type="button" class="btn btn-danger hidden" data-dismiss="modal">Start Over</button>
                    <button id="submitDialogBtn" type="button" class="btn btn-success hidden">Submit</button>
                </div>
              </div>

            </div>
        </div>

    {% else %} <!-- for: { if can_vote %} -->
        <div class="alert alert-warning" role="alert">
            <p>{{ cant_vote_reason }}</p>
        </div>
    {% endif %}
</div>
{% endblock %}

allauthdemo/templates/polls/generic_form.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
  <h1>{{ form_title }}</h1>
  {% load crispy_forms_tags %}
  <form method="post" action="" {{ form_attributes }} class="">
    {% crispy form %}
    <input class="btn btn-default" type="submit" value="Submit"/>
  </form>
</div>

{% endblock %}