allauthdemo/polls/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'polls'

#urlpatterns = [
#  url(r'^$', views.index, name='index'),
  # ex: /polls/5/
#  url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
  # ex: /polls/5/results/
#  url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
  # ex: /polls/5/vote/
#  url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#]

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),
]

allauthdemo/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', login_required(views.EventListView.as_view()), name='index'),
    url(r'^create/$', login_required(views.create_event), name='create-event'),
    url(r'^(?P<pk>[0-9a-f-]+)/$', login_required(views.EventDetailView.as_view()), name='view-event'),
    url(r'^(?P<pk>[0-9a-f-]+)/polls/$', login_required(views.EventDetailPollsView.as_view()), name='event-polls'),
    url(r'^(?P<pk>[0-9a-f-]+)/entities/$', login_required(views.EventDetailEntitiesView.as_view()), name='event-entities'),
    url(r'^(?P<pk>[0-9a-f-]+)/results/$', login_required(views.EventDetailResultsView.as_view()), name='event-results'),
    url(r'^(?P<pk>[0-9a-f-]+)/advanced/$', login_required(views.EventDetailAdvancedView.as_view()), name='event-advanced'),
    url(r'^(?P<event_id>[0-9a-f-]+)/end/$', login_required(views.event_end), name='end-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/edit/$', login_required(views.edit_event), name='edit-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/delete/$', login_required(views.del_event), name='del-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/decrypt/$', views.event_trustee_decrypt, name='decrypt-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/prepare/$', views.event_trustee_setup, name='prepare-event'),
    url(r'^(?P<event_id>[0-9a-f-]+)/bulletin_board/$', views.bulletin_boards, name='bulletin-boards'),
    url(r'^(?P<event_id>[0-9a-f-]+)/bulletin_board/(?P<poll_id>[0-9a-f-]+)/$', views.bulletin_board, name='bulletin-board'),
    url(r'^(?P<event_id>[0-9a-f-]+)/bulletin_board/(?P<poll_id>[0-9a-f-]+)/voter/(?P<voter_alias>[0-9a-f-]+)/$', views.voter_board, name='voter-board'),
    url(r'^(?P<event_id>[0-9a-f-]+)/poll/(?P<poll_id>[0-9a-f-]+)/vote/$', views.event_vote, name='event-vote'),
    url(r'^(?P<event_id>[0-9a-f-]+)/create/poll/$', login_required(views.manage_questions), name='create-poll'),
    url(r'^(?P<event_id>[0-9a-f-]+)/poll/(?P<poll_id>[0-9a-f-]+)/edit$', login_required(views.edit_poll), name='edit-poll'),
    url(r'^audit/$', views.vote_audit, name='vote_audit')
]

allauthdemo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

import allauthdemo.views
import allauthdemo.auth.views
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='visitor/landing-index.html'), name='landing_index'),
    url(r'^about$', TemplateView.as_view(template_name='visitor/landing-about.html'), name='landing_about'),
    url(r'^terms/$', TemplateView.as_view(template_name='visitor/terms.html'), name='website_terms'),
    url(r'^contact$', TemplateView.as_view(template_name='visitor/contact.html'), name='website_contact'),

    url(r'^event/', include('allauthdemo.polls.urls', namespace="polls")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', allauthdemo.auth.views.account_profile, name='account_profile'),

    url(r'^member/$', allauthdemo.views.member_index, name='user_home'),
    url(r'^member/events$', allauthdemo.views.MemberEvents.as_view(), name='account_events'),
    url(r'^member/action$', allauthdemo.views.member_action, name='user_action'),

    url(r'^admin/', include(admin.site.urls))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

allauthdemo/polls/polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render

from django.utils import timezone

from .models import Question, Choice

from django.views import generic


""" from allauthdemo.auth.forms import RegistrationForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegistrationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegistrationForm()

    return render(request, 'polls/index.html', {'form': form}) """


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
# ...
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

allauthdemo/polls/views.py
import urllib
import urllib2
import json
import logging
import base64

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.http.response import HttpResponseNotAllowed
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.conf import settings

from .forms import PollForm, OptionFormset, VoteForm, EventSetupForm, EventEditForm
from .models import Event, Poll, Ballot, EncBallot,  EncryptedVote, TrusteeKey, PartialBallotDecryption, CombinedBallot, VoteFragment, EmailUser
from allauthdemo.auth.models import DemoUser

from .tasks import email_trustees_prep, update_EID, generate_combpk, event_ended, create_ballots
from .tasks import create_ballots_for_poll, email_voters_vote_url, combine_decryptions_and_tally, combine_encrypted_votes
from .tasks import email_voting_success, email_organisers_next_steps

from .utils.EventModelAdaptor import EventModelAdaptor


class EventListView(generic.ListView):

    model = Event

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        return context


class EventDetailView(generic.DetailView):
    template_name = "polls/event_detail_details.html"
    model = Event

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        context['is_organiser'] = (not self.request.user.is_anonymous()) and (self.object.users_organisers.filter(email=self.request.user.email).exists())
        context['decrypted'] = self.object.status() == "Decrypted"

        # Get the results for all polls
        polls = self.object.polls.all()

        results = list()
        for poll in polls:
            result_json = poll.result_json

            if result_json is None:
                continue

            if result_json[len(result_json)-1] == ',':
                result_json = result_json[0:len(result_json)-1]

            result_json = json.loads(result_json)
            results.append(result_json)

        context['event_results'] = results

        return context


class EventDetailPollsView(EventDetailView):
    template_name = "polls/event_detail_polls.html"


class EventDetailEntitiesView(EventDetailView):
    template_name = "polls/event_detail_entities.html"


class EventDetailAdvancedView(EventDetailView):
    template_name = "polls/event_detail_advanced.html"


class PollDetailView(generic.View):
    model = Poll

    def get_context_data(self, **kwargs):
        context = super(PollDetailView, self).get_context_data(**kwargs)
        context['form'] = VoteForm(instance=self.object)
        context['poll_count'] = self.object.event.polls.all().count()
        return context


class EventDetailResultsView(EventDetailView):
    template_name = "polls/event_results.html"


def util_get_poll_by_event_index(event, poll_id):
    return event.polls.get(uuid=poll_id)


def edit_poll(request, event_id, poll_id):
    event = get_object_or_404(Event, pk=event_id)
    poll = util_get_poll_by_event_index(event, poll_id)

    if (poll == None):
        raise Http404("Poll does not exist")

    if request.method == 'GET':
        form = PollForm(instance=poll, prefix="main")
        formset = OptionFormset(instance=poll, prefix="formset_options")
        return render(request, "polls/generic_form.html", {'form_title': "Edit Poll: " + poll.question_text, 'form': form, 'option_formset': formset})
    elif request.method == 'POST':
        form = PollForm(request.POST, instance=poll, prefix="main")

        if form.is_valid():
            form.save()

            formset = OptionFormset(request.POST, instance=poll, prefix="formset_options")

            if formset.is_valid():
                formset.save()
                return HttpResponseRedirect(reverse('polls:event-polls', args=[poll.event_id]))


def vote_audit(request):
    encrypted_ballot = get_object_or_404(EncBallot, handle=''+urllib.quote_plus(request.GET.get('handle', None)))

    return render(request, "polls/vote_audit.html",
                  {
                      "ballot": encrypted_ballot.ballot
                  })


def event_vote(request, event_id, poll_id):
    event = get_object_or_404(Event, pk=event_id)

    if not event.prepared:
        messages.add_message(request, messages.WARNING, "This Event isn\'t ready for voting yet.")
        return HttpResponseRedirect(reverse("user_home"))

    # Lookup the specified poll
    poll = event.polls.get(uuid=poll_id)

    if poll is None:
        messages.add_message(request, messages.ERROR, "There was an error loading the voting page.")
        return HttpResponseRedirect(reverse("user_home"))

    polls = event.polls.all()
    event_poll_count = len(polls)
    prev_poll_uuid, next_poll_uuid, poll_num = False, False, 0
    can_vote, cant_vote_reason, has_voted, voter_email = False, "", False, ""

    for i in range(event_poll_count):
        poll = polls[i]
        poll_uuid = str(poll.uuid)
        req_poll_uuid = str(poll_id)

        if poll_uuid == req_poll_uuid:
            poll_num = str(i+1)

            # If current voting request isn't for the last poll, then make sure we link to the next
            if i != event_poll_count - 1:
                # Only set the previous poll's uuid if we're not looking at the first poll
                if i != 0:
                    prev_poll_uuid = str(polls[i - 1].uuid)

                next_poll_uuid = str(polls[i + 1].uuid)
            else:
                if i != 0:
                    prev_poll_uuid = str(polls[i - 1].uuid)

            break

    access_key = request.GET.get('key', None)
    email_key = event.keys.filter(key=access_key)
    email_key_str = email_key[0].key

    if email_key.exists() and event.voters.filter(email=email_key[0].user.email).exists():
        # Passing this test means the user can vote
        voter_email = email_key[0].user.email
        can_vote = True

        # Check whether this is the first time a user is voting
        ballot = Ballot.objects.filter(voter=email_key[0].user, poll=poll)
        if ballot.exists() and ballot[0].cast:
            has_voted = True
    else:
        can_vote = False
        cant_vote_reason = "You don't have permission to access this page."

    if event.status() != "Active":
        can_vote = False
        cant_vote_reason = "The event either isn't ready for voting or it has expired and therefore you cannot vote."

    if request.method == "POST":
        ballot_str = request.POST.get('ballot')
        ballot_json = json.loads(ballot_str)
        selection = request.POST.get('selection')
        encrypted_votes_json = ballot_json['encryptedVotes']

        enc_ballot_json = request.POST.get('encBallot')
        handle_json = request.POST.get('handle')

        # Adds or replaces the encrypted un-submitted ballot to the database for the auditor app to pick up later
        if EncBallot.objects.filter(handle=handle_json).exists():
            b = EncBallot.objects.get(handle=handle_json)
            b.ballot = enc_ballot_json
            b.save()
        else:
            b = EncBallot(handle=handle_json, ballot=enc_ballot_json)
            b.save()

        # Before storing the encrypted votes, we need the voter's ballot
        ballot, created = Ballot.objects.get_or_create(voter=email_key[0].user, poll=poll)
        EncryptedVote.objects.filter(ballot=ballot).delete()

        for e_vote in encrypted_votes_json:
            # Will store the fragments of the encoding scheme that define the vote
            encrypted_vote = EncryptedVote.objects.create(ballot=ballot)
            fragments_json = e_vote['fragments']

            for fragment in fragments_json:
                VoteFragment.objects.create(encrypted_vote=encrypted_vote,
                                            cipher_text_c1=fragment['C1'],
                                            cipher_text_c2=fragment['C2'])

        ballot.cast = True
        ballot.selection = selection
        ballot.json_str = ballot_str
        ballot.enc_ballot_handle = handle_json
        ballot.save()

        voter = email_key[0].user
        combine_encrypted_votes.delay(voter, poll)
        email_voting_success.delay(voter, handle_json, event.title)

        if next_poll_uuid:
            return HttpResponseRedirect(reverse('polls:event-vote', kwargs={'event_id': event.uuid,
                                                                            'poll_id': next_poll_uuid})
                                        + "?key=" + email_key_str)

        return HttpResponse('Voted Successfully!')

    return render(request, "polls/event_vote.html",
        {
            "object": poll, "poll_num": poll_num, "event": event, "poll_count": event.polls.all().count(),
            "prev_uuid": prev_poll_uuid, "next_uuid": next_poll_uuid, "min_selection": poll.min_num_selections,
            "max_selection": poll.max_num_selections, "can_vote": can_vote, "cant_vote_reason": cant_vote_reason,
            "voter_email": voter_email, "has_voted": has_voted, "a_key": email_key_str
        })


def event_trustee_setup(request, event_id):
    # Obtain the event and the event preparation access key that's been supplied
    event = get_object_or_404(Event, pk=event_id)
    access_key = request.GET.get('key', None)

    # If the a_key is present, check it's valid and related to a trustee EmailUser instance for this event
    if access_key:
        email_key = event.keys.filter(key=access_key)
        if email_key.exists() and event.users_trustees.filter(email=email_key[0].user.email).exists():
            if TrusteeKey.objects.filter(event=event, user=email_key[0].user).exists():
                return render(request, "polls/event_setup.html", {"is_trustee": True,
                                                                  "can_submit": False,

allauthdemo/templates/bases/bootstrap-auth.html
{% extends "bases/bootstrap-minimal.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 big-box">
    {% block inner-content %}
    {% endblock %}
    </div>
  </div>
</div><!-- container -->
{% endblock %}

allauthdemo/templates/bases/bootstrap-member.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}
{% block nav %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'user_home' %}">Demo Members Area</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'user_home' %}">Home</a></li>
            <li><a href="{% url 'user_action' %}">Action</a></li>
            <li><a href="{% url 'polls:index' %}">Events</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <strong> {{ user.display_name }}</strong> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Account</li>
                <li><a href="{% url 'account_profile' %}"><i class="fa fa-cog"></i> Settings</a></li>
                <li><a href="{% url 'account_events' %}"><i class="fa fa-bell"></i> My Events</a></li>
                <li><a href="{% url 'account_email' %}"><i class="fa fa-envelope"></i> Email Addresses</a></li>
                <li><a href="{% url 'socialaccount_connections' %}"><i class="fa fa-facebook"></i> Social Networks</a></li>
                <li><a href="{% url 'account_change_password' %}"><i class="fa fa-lock"></i> Change Password</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> Sign Out</a></li>
              </ul>
            </li>
            <li>{% if user.profile.avatar_url %}<img alt="" style="width:50px; height:50px" src="{{user.profile.avatar_url}}">{% endif %}</li>
          </ul>
        </div>
      </div>
    </div>

{% endblock %}

allauthdemo/templates/bases/bootstrap-minimal.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}

{% block nav %}
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src='{% static "img/demos-banner.png" %}' style="height:100%" title="demos2"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'landing_index' %}"><strong>Home</strong></a></li>
            <li><a href="{% url 'account_signup' %}"><strong>Join</strong></a></li>
            <li><a href="{% url 'account_login' %}"><strong>Log In</strong></a></li>
          </ul>
        </div>
      </div>
    </div>
{% endblock %}

allauthdemo/templates/bases/bootstrap-visitor.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}

{% block nav %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src='{% static "img/demos2-banner.png" %}' style="height:100%" title="demos2"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'landing_index' %}">Home</a></li>
            {% comment %}<li><a href="{% url 'landing_about' %}">About</a></li>{% endcomment %} <!-- Currently this is not a production-ready page -->
            <li><a href="{% url 'polls:index' %}">Events</a></li>
            <li><a href="{% url 'account_signup' %}"><strong>Join</strong></a></li>
            <li><a href="{% url 'account_login' %}"><strong>Log In</strong></a></li>
          </ul>
        </div>
      </div>
    </div>

{% endblock %}

allauthdemo/templates/bases/bootstrap-with-nav.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}

{% block nav %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src='{% static "img/demos2-banner.png" %}' style="height:30px" title="demos2"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'landing_index' %}">Home</a></li>
            {% comment %}<li><a href="{% url 'landing_about' %}">About</a></li>{% endcomment %} <!-- Currently this is not a production-ready page -->
            <li><a href="{% url 'polls:index' %}">Events</a></li>
            {% if user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <strong> {{ user.display_name }}</strong> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">Account</li>
                  <li><a href="{% url 'account_profile' %}"><i class="fa fa-cog"></i> Settings</a></li>
                  <li><a href="{% url 'account_events' %}"><i class="fa fa-bell"></i> My Events</a></li>
                  <li><a href="{% url 'account_email' %}"><i class="fa fa-envelope"></i> Email Addresses</a></li>
                  <li><a href="{% url 'socialaccount_connections' %}"><i class="fa fa-facebook"></i> Social Networks</a></li>
                  <li><a href="{% url 'account_change_password' %}"><i class="fa fa-lock"></i> Change Password</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> Sign Out</a></li>
                </ul>
              </li>
              <li>{% if user.profile.avatar_url %}<img alt="" style="width:50px; height:50px" src="{{user.profile.avatar_url}}">{% endif %}</li>
            {% else %}
              <li><a href="{% url 'account_signup' %}"><strong>Join</strong></a></li>
              <li><a href="{% url 'account_login' %}"><strong>Log In</strong></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

{% endblock %}

allauthdemo/templates/bases/bootstrap.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" {% block htmlattr %}{% endblock %}>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}DĒMOS 2{% endblock %}</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  {% block head_css %}
  <link rel="stylesheet" media="screen" href='{% static "css/main.css" %}'>
  {% endblock %}

</head>
<body class='{% block pageclass %}{% endblock %}' {% block bodyattr %}{% endblock %}>

{% block nav %}{% endblock %}

{% block content %}{% endblock %}

{% block footer %}
<div class=container>
  <hr>
  <footer>
    <ul class="list-inline pull-right">
      <li><a href="{% url 'website_terms' %}">Terms</a></li>
      <li><a href="{% url 'website_contact' %}">Contact</a></li>
    </ul>
    <p class=muted>{% include "copyright.html" %}</p>
  </footer>
</div>
{% endblock %}

{% block tail_js %}
{% endblock %}

</body>
</html>